# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01d79a55d0b34f77ead4046f860981bb100bb2f08891d1bd8604c076a5726329bd1f839633e1d34c308080563fae31ede39729db6a4d9e7a66852d8a872a7930

test:
  secret_key_base: a350093c5e0521888cf1e12205f9f020673cb97e8cb8ea964294145df3f68f4c604041824850f050da8714882f0558ed27ff940ba988169f620e74012cd83d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
